version: v2
environments: []
pipeline:
  - name: build
    continue_on_failure: false
    image: 'maven:3.6-jdk-11'
    script:
      - mvn package -DskipTests=true
    artifact_path:
      - all/target
    cache: []
  - name: deploy
    pipe: 
      name: cord/deploy
      config: 
        environment: gabito
